version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - /zookeeper/data:/var/lib/zookeeper/data
      - /zookeeper/log:/var/lib/zookeeper/log
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.28.14.13
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_LOG_CLEANER_ENABLE: 'false' # -> brrt tidak di compact alias di delete (compact: hanya state terakhir yang di pertahankan, yang lama di delete)
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 20000 # expire mau di compact atau di delete -> 20000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 10000 # sebelum di delete di keep brp lama in ms ya
      KAFKA_LOG_FLUSH_SCHEDULER_INTERVAL_MS: 2000 # scheduler flush interval brp kali checkingnya
      KAFKA_LOG_MESSAGE_FORMAT_VERSION: 0.8.2
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000 # check interval
      KAFKA_LOG_RETENTION_MINUTES: 1440
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
    volumes:
      - /kafka-local:/kafka/kafka-logs
      - /var/run/docker.sock:/var/run/docker.sock
